#!/usr/bin/env bash
# Read content of file 
# only display: username, user id, Home directory path for the user
FILE=/etc/passwd

while read -r line; do
	echo "$(echo $line | cut -d: -f1):$(echo $line | cut -d: -f3):$(echo $line | cut -d: -f6)"
done < "$FILE"
