#!/usr/bin/env bash
# A script that displays the contents of the /etc/passwd file, using the while loop + IFS.

while IFS= read -r line; do
	echo "The user $(echo "$line" | cut -d: -f1) is part of the $(echo "$line" | cut -d: -f4) gang, lives in $(echo "$line" | cut -d: -f6) and rides $(echo "$line" | cut -d: -f7). $(echo "$line" | cut -d: -f3)'s place is protected by the passcode $(echo "$line" | cut -d: -f2), more info about the user here: $(echo "$line" | cut -d: -f5)"
done < /etc/passwd
