#!/usr/bin/env bash
# A script to print a message 10 times with if statement.
i=1
while [ $i -ne 11 ]
do
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
