#!/usr/bin/env bash
# A script to test the behavior of the while and if loop.
while [ $i -le "20" ]
do
    case $i in
        4)
            echo $i
            echo "bad luck from China"
            ;;
        9)
            echo $i
            echo "bad luck from Japan"
            ;;
        17)
            echo $i
            echo "bad luck from Italy"
            ;;
        *)
            echo $i
            ;;
    esac

    (("i += 1"))
done
