#!/usr/bin/env bash
file="school"

if [ -e "$file" ]; then &&  && [ -f school ]
	echo "$file file exists"
	if [ -s "$file" ]; then
		echo "$file file is not empty"
	else
		echo "school file is empty"
	fi


	if [ -f "$file" ]; then 
		echo "$file file is a regular file"
	fi

else
	echo "school file does not exist"
fi
