#!/usr/bin/env bash
# A script that gives information about a file `school`.

FILE="school"
if [ -e "$FILE" ]; then
	echo "school file exists"
	if [ ! -s "$FILE" ]; then
		echo "school file is empty"

		if [ -f "$FILE" ]; then
			echo "school file is a regular file"
		fi
	else
		echo "school file is not empty"

		if [ -f "$FILE" ]; then
			echo "school file is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
