#!/usr/bin/env bash
# A script that gives information about a file
file="school"

if test -e "$file"
then
	echo "$file file exists"

	if test ! -s "$file"
	then
		echo "$file file is not empty"
	else
		echo "school file is empty"
	fi


	if test -f "$file"
	then 
		echo "$file file is a regular file"
	fi

else
	echo "school file does not exist"
fi
